import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Esakwa Nkongo Nathan's portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
